# Dockerfile.dev
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY requirements_dev.txt requirements_dev.txt

RUN pip install --no-cache-dir -r requirements.txt -r requirements_dev.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8030", "--reload"]
